# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Akhilesh_Personal

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UiPathDeploy@4
  inputs:
    toolpath: 'C:\Users\akhileshk3\AppData\Local\Programs\UiPath\Studio\UiRobot.exe'
    orchestratorConnection: 'con_Orchestrator'
    packagesPath: 'C:\Users\akhileshk3\Documents\UiPath\Azure_Test'
    folderName: 'akhil.kalg067@gmail.com''s workspace (Converted)'
