# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Akhilesh_Personal

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: | 
          $Env:Uipath_toolpath = 'C:\Users\akhileshk3\AppData\Local\Programs\UiPath\Studio\UiRobot.exe'
          Write-Host  "Uipath_toolpath set to $Env:Uipath_toolpath"
          displayname: 'Set Uipath_toolpath'
- task: UiPathInstallPlatform@4
  inputs:
    cliVersion: 'WIN_23.10.8894.39673'
- task: UiPathRunJob@4
  inputs:
    orchestratorConnection: 'con_Orchestrator'
    processName: 'Azure_Test'
    folderName: 'akhil.kalg067@gmail.com''s workspace (Converted)'
    user: 'C:\Users\akhileshk3'
    machine: 'BSBLRL-16320'
